### ISSUE TITLE
DDNS Update fails with invalid TSIG using v3.0.2

### ISSUE THREAD

**Issue by gribnut** [dnsjava/dnsjava#100]
Recently updated dnsjava from 2.1.9 to 3.0.2.  After update, DDNS updates failed with invalid TSIG response from nameserver.  Was using constructor of TSIG(String name, String key) with default algorithm of hmac-md5.  Also tried specifying HMAC-MD5 algorithm Name with same result. 

Sample code (works in v2.1.9 but fails with 3.0.2):
`        
        resolver.setTSIGKey(new TSIG(TSIG.HMAC_MD5, keyname, zone.getTsig_priv_key()));
        resolver.setTCP(true);
        response = resolver.send(update);
        log.trace("DDNS Response:\n{}",response.toString());
` 
Response from (BIND 9.11.x nameserver) when using dnsjava 3.0.2:
;; ->>HEADER<<- opcode: UPDATE, status: SERVFAIL, id: 46875
;; flags: qr ; qd: 1 an: 0 au: 0 ad: 0 
;; TSIG invalid

**Comment by ibauersachs** [comment]
I'll look into it. Is there any chance you could provide a Wireshark trace?

**Comment by gribnut** [comment]
Thanks Ingo.  Attached packet capture from failed DDNS update using dnsjava v3.0.2 and successful DDNS update using dnsjava v2.1.9. 
[dnsjava-3-0-2.dump.gz](https://github.com/dnsjava/dnsjava/files/4488616/dnsjava-3-0-2.dump.gz)
[dnsjava-2-1-9.dump.gz](https://github.com/dnsjava/dnsjava/files/4488619/dnsjava-2-1-9.dump.gz)

**Comment by ibauersachs** [comment]
Thanks! In v3 EDNS0 is enabled by default and the message rendering breaks in combination with TSIG,  the bug is already present in 2.1.9. As a workaround until I have a fix ready, you can disable EDNS0 (call `SimpleResolver.setEDNS(-1);`).

@demonti can you help me out here? The issue is that in `Message.toWire(int maxLength)` the OPT record is put last into the additional section of an already signed message. Might have been broken before your truncation patch (see commit 29b72d7649c7d4d1a591ea716306b9e6a90a0e8a). Note that in this case the message is signed by the resolver, i.e. `tsigkey` is null.

https://tools.ietf.org/html/rfc6891#section-6.1.1:
 >    The OPT RR MAY be placed anywhere within the additional data section.
   When an OPT RR is included within any DNS message, it MUST be the
   only OPT RR in that message.  If a query message with more than one
   OPT RR is received, a FORMERR (RCODE=1) MUST be returned.  The
   placement flexibility for the OPT RR does not override the need for
   the TSIG or SIG(0) RRs to be the last in the additional section
   whenever they are present.

https://tools.ietf.org/html/rfc2845
> 3.1. Effects of adding TSIG to outgoing message
>
 >  Once the outgoing message has been constructed, the keyed message
   digest operation can be performed.  The resulting message digest will
   then be stored in a TSIG which is appended to the additional data
   section (the ARCOUNT is incremented to reflect this).  If the TSIG
   record cannot be added without causing the message to be truncated,
   the server MUST alter the response so that a TSIG can be included.
   This response consists of only the question and a TSIG record, and
   has the TC bit set and RCODE 0 (NOERROR).  The client SHOULD at this
   point retry the request using TCP (per [RFC1035 4.2.2]).

**Comment by gribnut** [comment]
Thanks again @ibauersachs.  I've updated to v3.0.2 and verified your suggested workaround of disabling EDNS0 (mimicking 2.1.9 behavior) is successful in my testing.

**Comment by demonti** [comment]
The problem is that the original author provided multiple ways of applying TSIG data to a message and that there are inconsistencies within the toWire methods.

Message class:
- The toWire method **with** a maximum length is capable of doing the TSIG generation on its own. One has to provide the TSIG key to the Message instance and then this will happen magically and correctly.
- The toWire method **without** a maximum length is not capable to perform the signing, it is also not capable dealing correctly with the OPT record.

TSIG class:
- The "generate" method generates the TSIG record for a given message, whereas
- The "apply" method not only generates the TSIG record, but also adds it to the message

The problematic behaviour occurs if TSIG.apply is used in combination with Message.toWire (maxLength). In this case the toWire method is unaware that a TSIG record exists and places the OPT record after the (unknown) TSIG record. Unfortunately, the SimpleResolver.sendAsync (message, forceTcp) seems to do exactly this.

For the bug fix, I suggest to supply the TSIG key to the message instead of using the apply method.

For clean-up it is not that easy.

- On the one hand, the Message.toWire method (without maxLength) is problematic for being used by the public as it does not do any OPT and TSIG processing at all, on the other hand, it is required by TSIG to calculate the hash of the original message. Maybe one could separate the uses and change the public version to share code with the method using the maximum length.
- The TSIG.apply method is problematic as well, as it creates the above trouble. Maybe (I don't know the side effects in user code), it would be sufficient to simply add itself to the message and let the Message class doing the nitty-gritty details. This makes the toWire clean-up mentioned in the item before necessary.

**Comment by demonti** [comment]
One addition: the toWire method (without maxLength) is only used by TSIG.apply and not by TSIG.generate. So with the the TSIG.apply fix, the old functionality is then no longer required for the TSIG generation (maybe there are other uses, however – I have not searched for them).

**Comment by ibauersachs** [comment]
I went for the most simple route now: set the tsig-key on the message so `toWire(int)` adds the signature and updated documentation. `toWire()` is used in other places and it can be desirable to have a method that does not fiddle with the message content.
@demonti can you have a quick look at #108 please?
