### ISSUE TITLE
Make org.xbill.DNS.Record class Serializable

### ISSUE THREAD

**Issue by ironluca** [dnsjava/dnsjava#114]
It helps in many situations, in addition, per the code, all the internal state of the Record and its sub-classes are Serializable. Serializable would be useful in place where the record has to be propagated to network for different parts of the system.

**Comment by ibauersachs** [comment]
There is a very well defined serialization of Records: it's called DNS.
I intentionally removed the Serializable interface because the SerialVersionUID was not kept up to date and because java-binary serialization of Records is pointless with two already existing format (zone file format / DNS wire protocol). Additionally with Record now having a public constructor, it's not guaranteed to work anymore for all record types.

**Comment by ironluca** [comment]
While I understand the above line of reasoning. Record being serializable would be useful in a few situations, as I am encountering. Just to highlight, I am using the records in a BPMN workflow context where the process state is serialized on encountering a User Task and reloaded for subsequent tasks. In this case, of course, the work around is to form a separate class with minimal information from the Record and make that Serializable.

However, as mentioned earlier, I appreciate why you don't want to make the class serializable, there are use cases where it would be actually very useful.
