### ISSUE TITLE
DOH resolver to support persistent connection

### ISSUE THREAD

**Issue by devrivne** [dnsjava/dnsjava#123]
From what I'm seeing, DOH resolver creates a new connection on each lookup that issues to:
With light load
```
$ netstat -natp | grep here-doh-server-ip  |wc -l
865
```

With a slihtly increased load:
```
$ sudo netstat -natp | grep here-doh-server-ip  |wc -l
7120
```

Logs:
```
java.util.concurrent.CompletionException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
java.util.concurrent.CompletionException: java.io.IOException: too many concurrent streams
[86.730s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
```

Also, is it possible to add connection pool?

**Comment by ibauersachs** [comment]
Which version of Java did you use for this test? If it is Java 8, then I won't bother about it as this cannot use the recommended HTTP v2.

**Comment by devrivne** [comment]
It was tested on on 11 and 8 versions.

**Comment by ibauersachs** [comment]
I did a quick test and cannot reproduce this. HTTP keepalive is enabled by default on Java 11 (and 8 as well). You need to reuse the `DohResolver` instance though. If you create `DohResolver` per request, it will create a new [HttpClient](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html) and thus new threads and new connections. `DohResolver` is thread safe unless you use TSIG.

**Comment by devrivne** [comment]
There is no sense in creating a resolver per request.
```
val resolver = new org.xbill.DNS.DohResolver("https://cloudflare-dns.com/dns-query")
resolver.setTimeout(timeout)
resolver.sendAsync(message).toCompletableFuture()
```

Trying to resolve from 200 up to 1000 domains per second asynchronously.

**Comment by ibauersachs** [comment]
**Java 11**
Okay, so this is pretty interesting and annoying at the same time. The Java 11 HttpClient reuses the connection, but only once it was sucessfully negotiated as HTTP_2. Before that, connections are blindly created. [JDK-8195137](https://bugs.openjdk.java.net/browse/JDK-8195137) loosely describes this behavior. If you run an example with the DohResolver which sends one synchronous query to create a successful HTTP_2 connection, then do hundredes of queries in parallel, you'll see that only one TCP connection is created. Wheres if you skip the initial synchronous query, hundreds of connections are created. I haven't found anything to configure this behavior, and interpreting the JDK bug comments this is intentional. I'm not sure this is really fixable. Also, the HttpClient uses an unbounded thread pool by default... 

The only idea I have is to make the first query to DohResolver synchronous. However, this needs to take idle periods into account when a connection can timeout (based on jdk.httpclient.keepalive.timeout). There is no client side connection timeout for HTTP/2 and the server-side idle timeout is not visible via API.

**Java 8**
Only HTTP/1.1 is available, which is not recommended for DoH. Anyway, the default is to use Keepalive, but the implementation is so obscure that you need to manually set the same socket factory on the connection that connections are actually reused. And if more than `http.maxConnections` are created, the socket starts lingering around.

All in all, if you need this in a high-load production environment, I'd suggest you write something on your own that uses a sane HTTP library, e.g. with OkHttp or Netty.

**Comment by devrivne** [comment]
Hello
 
Now everything clear for me.
Will try to initiate synchronous call at first.
Also, I've tried DOH resolver based on Akka.Http, 
but dnsjava doh resolver even with a huge num of connections works much faster.

Great job!
Many thanks.

**Comment by ibauersachs** [comment]
> Hello
> 
> Now everything clear for me.
> Will try to initiate synchronous call at first.

The DohResolver does exactly that based on the timeout value you can supply in the new constructor.

> Also, I've tried DOH resolver based on Akka.Http,
> but dnsjava doh resolver even with a huge num of connections works much faster.
> 
> Great job!
> Many thanks.
