### ISSUE TITLE
IntelliJ/Android Studio warns about blocking code in coroutines

### ISSUE THREAD

**Issue by gnarea** [dnsjava/dnsjava#146]
Initialising classes like `Name` and `Message` results in warnings like `Inappropriate blocking method call` in IntelliJ (and potentially other static code analysers), because those constructors could throw a `TextParseException`, which is considered a blocking call because that exception extends `IOException`.

![intellij-dnsjaja](https://user-images.githubusercontent.com/369863/103171365-92edd180-4843-11eb-9020-9c8ddb68b149.png)

https://github.com/dnsjava/dnsjava/blob/1d0577c604fe71b3ca4cc36f19c459cbc4eb134b/src/main/java/org/xbill/DNS/TextParseException.java#L12

I don't think this causes any actual runtime issues, but it's confusing for those of us using this library for the first time.

**Comment by ibauersachs** [comment]
I don't think there's much I can do about that. Chaging the base class of `TextParseException` would cause a major API break. Also, by looking at the JDK-defined exceptions that derive from IOException, e.g. [CharacterCodingException](https://docs.oracle.com/javase/8/docs/api/java/nio/charset/CharacterCodingException.html), I think IOException is actually an appropriate base class.

Showing a warning just because something might throw an IOException seems very aggressive. Have you considered reporting this to JetBrains? Or is there something else that can be done in a library to suppress such a warning, e.g. an `@NonBlocking`  annotation?

**Comment by gnarea** [comment]
Hi. Thanks for looking into this.

I agree there's not much you can do at this point -- I mainly wanted to raise this issue in case you're planning a major release and wanted to ship a breaking change to avoid this warning.

I've just found there two issues where others also complaint about the inspection so I've just upvoted them:

- https://youtrack.jetbrains.com/issue/IDEA-243869
- https://youtrack.jetbrains.com/issue/KT-39352

In the meantime, I'll use the `@Suppress("BlockingMethodInNonBlockingContext")` annotation.

**Comment by ibauersachs** [comment]
The two referenced JetBrains issues are now closed and I couldn't reproduce the warnings with IntelliJ 2021.3.
