### ISSUE TITLE
Clean shutdown when run inside Tomcat

### ISSUE THREAD

**Issue by AndrewDodd42** [dnsjava/dnsjava#180]
I am using dnsjava inside a web-app running under Tomcat and I am getting the following error when the web-app is reloaded.

`24-Mar-2021 11:03:16.941 WARNING [Catalina-utility-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [dnsjava NIO selector] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.9.1/sun.nio.ch.KQueue.poll(Native Method)
 java.base@11.0.9.1/sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:122)
 java.base@11.0.9.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
 java.base@11.0.9.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
 org.xbill.DNS.Client.runSelector(Client.java:67)
 org.xbill.DNS.Client$$Lambda$291/0x0000000800493c40.run(Unknown Source)
 java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)`

It appears as though the Client selector and associated thread is closed in the shutdown hook. Is there a way to manually close this during the web-app unloading?

I've never written a PR before but I'm happy to try adding a manual close() if necessary.

**Comment by ibauersachs** [comment]
The class that spins up the selector thread is currently package-private and I would very much prefer to keep it that way. Is there a possibility to register a hook for web-apps, similar to the runtime shutdown hook?

**Comment by AndrewDodd42** [comment]
Keeping the class package-private definitely makes sense. The ServletContextListener class allows code to register for web-app context initialisation and destruction events. This can be registered either through the web.xml file or a @WebListener annotation.

I'm happy to experiment with hooking things in this way.

**Comment by ibauersachs** [comment]
Hm, the `ServletContextListener` isn't part of the Java SE8 API, so I'm not sure I can rely on that. Let me think about this a bit.

As a workaround in the meantime you can call `org.xbill.DNS.Client#close` via reflection from an `@WebListener` method of your own. But please note that `close()` method currently assumes the JVM is shutting down and thus doesn't continue cleaning up when one of the steps fails.

**Comment by AndrewDodd42** [comment]
Including a dependency on the Servlet API does seem a bit extreme!

Using reflection to call close() hadn't occurred to me but I think I can see how to make it work. I don't think that close() assuming that the JVM is shutting down will be a problem. When the web-app restarts it comes back with a new ClassLoader and an entirely fresh set of classes anyway.

**Comment by ibauersachs** [comment]
Calling close shouldn't be a problem by itself, but if an exception happens while closing, you might still have a resource leak. Not assuming that JVM is shutting down anyway, close() should handle failures more gracefully and try to close as many resources as possible.

**Comment by AndrewDodd42** [comment]
If close() could handle failures more gracefully then that would be reassuring.

The reflection based WebListener works well and has stopped Tomcat complaining about the thread, thanks again for the suggestion. I also added in a synchronised check on the selector field to catch the situation where dnsjava hasn't been initialised before the web-app is restarted.

**Comment by nresare** [comment]
While it is good that you found a way to resolve the immediate problem I think that we should expose some mechanism to have dnsjava manage it's resources without resorting to reflection tricks.

There are a few moving pieces that needs to land before that could be reality, but I think that having LookupSession implement `AutoCloseable` and stop the IO threads on close would be the cleanest way to accomplish this.

**Comment by ibauersachs** [comment]
@nresare I was thinking of exposing a static `close()` method in e.g. the `Client` class or a new `Dnsjava` class. While having LookupSession implementing AutoClosable is a good idea, I think it should interact with the legacy `Lookup` and `SimpleResolver`. A reference counter in `Client` could deal with not throwing away the thread when it wasn't created with LookupSession, but _also_ used with LookupSesison(s).

**Comment by AndrewDodd42** [comment]
Thanks for adding the NioClient.close() method! It's working well in my situation. I'm interested in using LookupSession in the future so having AutoCloseable support there sounds like it would be useful too.

**Comment by jlanawalt** [comment]
@AndrewDodd42 did you add it to a ServletContextListener? I have and when debugging contextDestroyed gets called on deploy and NioClient.java:93 throws NullPointerException, likely due to selector being null. I'm not sure how to protect against that except by first calling NioClient.selector().

Putting NioCLient.close() into contextDestoryed does get rid of the clearReferencesThreas warning about dnsjava NIO selector leaving only the familiar occasional warning about a thread with ResolverConfigurationImpl in the stack.

**Comment by enexusde** [comment]
```31-Mar-2024 08:23:02.704 SCHWERWIEGEND [http-nio-8080-exec-25] de.e_nexus.web.rm.mail.veto.dnsbl.DNSThreadStopper.stopDNSThreads Could not shutdown [dnsjava NIO selector]!
java.lang.NullPointerException: Cannot invoke "java.nio.channels.Selector.wakeup()" because "org.xbill.DNS.NioClient.selector" is null
	at org.xbill.DNS.NioClient.close(NioClient.java:89)
	at org.xbill.DNS.NioClient.close(NioClient.java:67)
	at de.e_nexus.web.rm.mail.veto.dnsbl.DNSThreadStopper.stopDNSThreads(DNSThreadStopper.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
31-Mar-2024 08:23:50.761 WARNUNG [http-nio-8080-exec-25] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [dnsjava NIO selector] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@17.0.6/sun.nio.ch.EPoll.wait(Native Method)
 java.base@17.0.6/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:118)
 java.base@17.0.6/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
 java.base@17.0.6/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
 org.xbill.DNS.NioClient.runSelector(NioClient.java:113)
 org.xbill.DNS.NioClient$$Lambda$5994/0x0000000807912710.run(Unknown Source)
 java.base@17.0.6/java.lang.Thread.run(Thread.java:833)

```

**Comment by frozenice** [comment]
Sorry for resurrecting, but I noticed that the selector thread still lingers around (using v3.6.5 in Tomcat with a custom plugin-system with load/unload). @ibauersachs would you kindly take a look?

It seems the `selectorThread` is stuck in a self-join:

```java
// massively shortened
selectorThread = new Thread(NioClient::runSelector);

static void runSelector() {
  while (run) { }
  runClose(); // only place that calls it
}

private static void runClose() {
  Thread localSelectorThread = selectorThread;
  localSelectorThread.join(); // self-join
}
```

I am currently using this workaround:

```kotlin
NioClient.close()
val nioThread = Thread.getAllStackTraces().keys.find { it.name == "dnsjava NIO selector" }
nioThread?.interrupt()
nioThread?.join(500)
```

That gets rid of the thread, though it would be better if this is fixed in the library (great library btw).

The javadoc of `public static void close()` states:

> Does not wait until the selector thread has stopped.

So maybe remove the `if (localSelectorThread != null) {` block completely?

Although it just calls `private static void close(boolean fromHook)` and that doesn't specify if the intention is to wait for the thread to finish or not. If it should wait, then you'd probably have to (in addition to removing the mentioned block) save `selectorThread` to a local variable in the private `close(boolean)` (before `runClose()` nulls it) and `.join()` on that at the end.

Personally, when working with libraries, I prefer a public shutdown method that actually waits until everything is cleaned up - with the wait either being implicit (documented) or explicit (as a boolean parameter, another method, or a returned `Future` or such).

**Comment by ibauersachs** [comment]
I messed that up in 3efb25e0cc2414ef1491669bc56e409746c23f21. I'll have a look, but I'm not sure which way to go with waiting until the selector thread is gone.
