### ISSUE TITLE
Unnecessary synchronization in org.xbill.DNS.Header::getID

### ISSUE THREAD

**Issue by maltalex** [dnsjava/dnsjava#215]
I'm working on improving the performance of a project that deals with enormous amounts of dns messages. One of the performance bottlenecks I'm seeing is a whole lot of locking in `org.xbill.DNS.Header::getID` which is implemented like this:

```
private static final Random random = new SecureRandom();

public int getID() {
  synchronized (random) {
    if (id < 0) {
      id = random.nextInt(0xffff);
    }
    return id;
  }
}
```

The implementation is not only synchronized - it's synchronized around a `static` object, meaning that all `getID` calls in all `Header` instances are serial! Note that `SecureRandom` itself is thread-safe and doesn't require locking.

Could the `getID` implementation be changed to be lock-free using a `volatile` variable or an `AtomicInteger`? Or at least switched to use per-instance locking (e.g. synchronize on `this` or some other non-null field) to reduce the lock's scope?

I'd be happy to submit a PR with a lock-free implementation.

**Comment by ibauersachs** [comment]
An `AtomicInteger` would generate predictable results, which is a no-go to avoid the Kaminsky attacks. Since SecureRandom is thread safe, the synchronization around it can be removed. And volatile would can be avoided by always generating an id (instead of -1) in the no-arg constructor.

If you open a PR, you may want to create it against the release/3.4.x branch as master won't get a new release soon.

**Comment by ibauersachs** [comment]
> I was suggesting using an `AtomicInteger` not for id generation, but for storing the id and setting it using an atomic, lock-free `compareAndSet`.

Ah, I see.

> > And volatile would can be avoided by always generating an id (instead of -1) in the no-arg constructor.
> 
> That would be the best option IMHO. But but then we lose the lazy initialization of the ID field, which looks like the intention of the author of that class. Using `SecureRandom` too much can also be extremely slow (when low on entropy), so if there are use cases that generate many `Header` instances but don't need to initialize their ID field, they'd see worse performance due to this change. Is that a common scenario?

The default implementation of SecureRandom is SHA1PRNG, which AFAIK doesn't do reseeds and thus will never run out of entropy. I wouldn't know when an unset ID would be useful. Answers coming from the network have an ID which is parsed, and sending request need an ID anyway. The only case where the ID must be statically `0` is DNS over HTTP since the protocol is TCP and the order of delivery is guaranteed.

**Comment by bwelling** [comment]
The reason for the lazy initialization, as far as I remember, was to avoid needing to generate a random ID that would immediately be overridden when parsing a header from wire format.  It's possible that this is no longer needed; there is an alternate constructor that specifies the ID, and it's used when constructing a header from wire format (which is likely the common case; I'm not sure if there's any other code that separates the construction and parsing).

(and for the record, DoH doesn't require an ID of 0, it's a SHOULD.  It's also not because of ordered delivery, it's because `the use of a varying DNS ID can cause semantically equivalent DNS queries to be cached separately`.  With HTTP/2, there's no guarantee that responses will be ordered, but they will be correlated by HTTP stream.)

**Comment by ibauersachs** [comment]
Yes, you're right, I forgot about the DoH http-based caching. I don't have the project open ATM to search for references, but if parsing the message creates an empty Header instance, we should change that. But I assume that's already the case.

If the SecureRandom performance really turns out to be an issue I think we can revisit that later.

**Comment by maltalex** [comment]
> But I assume that's already the case.
It is. I took a glance at the parsing code before submitting the PR.

The `Message` constructors that take a `byte[]` or `ByteBuffer` call `Header(DNSInput in)`, which in turn calls `this(in.readU16());`.
So it looks like the parsing flow creates the header with the ID from the wire.
