### ISSUE TITLE
How to get the chain of DS/DNSKEY records used to verify DNSSEC?

### ISSUE THREAD

**Issue by gnarea** [dnsjava/dnsjava#255]
# What I need to do

I need to store the response of a `TXT` record along with all the DNSSEC-related data necessary for that `TXT` record response to be independently verified by another component in a decentralised system.

# What I'm trying

I'm basically using the [DNSSEC resolver example](https://github.com/dnsjava/dnsjava/blob/master/EXAMPLES.md#dnssec-resolver), but I'm finding that `response` only contains the `TXT` and its respective `RRSIG`.

Is there any way to also get all the `DNSKEY`s that this library internally queried to do the DNSSEC validation?

**Comment by ibauersachs** [comment]
Hey,
I understand the idea and I'd like to have something in the library that could provide the entire validation path, e.g. to print the chain with GraphViz. However, I so far I didn't have time to properly implement anything. 
A rough idea I have is to pass a context along the entire lookup that can be used for both regular logging as well as adding the used DS/DNSKEY/RRSIG records. the `FindKey` phase already has a state object that is passed along the various lookups of a key.

I'm at this point very reluctant to make any of the dnssec classes public. It would limit further refactorings (e.g. to introduce the aforementioned context/state parameter) without breaking the API.

> Is there any way to also get all the DNSKEYs that this library internally queried to do the DNSSEC validation?

You could probably try to set a custom `Cache` implementation on the Resolver to access all used records.

**Comment by gnarea** [comment]
Hi @ibauersachs. Thanks for your reply!

I totally understand your concern regarding refactoring. It's definitely best to think through what public API to offer to expose this functionality, rather than just making certain elements `public`.

Since you haven't been able to implement it due to time constraints, what would be the best way to make it happen? Should we discuss the design a bit more and then I create a PR? Or can we sponsor this work?

Let me give you a bit more context in case it's helpful:

Having the `ValidatingResolver` output the DS/DNSKEY/RRSIG records would be nice, but the most important thing is to be able to do the DNSSEC verification independently of the resolver. Imagine we have the DS/DNSKEY/RRSIG records in a file -- we should be able to parse that file and do the DNSSEC verification without using the Internet.

In case you wonder why we need that, it's to make DNS partly work for people who don't have a connection to the Internet or whose connection is intermittent. I'm currently building a prototype of [Vera](https://vera.domains/) to do just that, but I'm having to use a temporary fork of dnsjava to get on with it.

Obviously we wouldn't want to use that fork when/if we build the real thing, which is why I'm interested in seeing if/how I can help make it happen in dnsjava itself.

**Comment by gnarea** [comment]
Actually, I think moving the records to the `verify()` method would make more sense:

```kotlin
val verifier = DNSSECVerifier(
  ". IN DS 20326 8 2 E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D",
)

val verifiedRRSet = try {
  verifier.verify(
    txtRRSet,
    listOf(isgOrgDNSSECZone, orgDNSSECZone),
    rootDNSKEY,
  )
} catch (exc: DNSSECVerificationException) {
  throw AnotherException("DNSSEC verification failed", exc)
}
```

or...

```kotlin
val verifier = DNSSECVerifier(
  ". IN DS 20326 8 2 E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D",
)

val verifiedRRSet = try {
  verifier.verify(dnsResponse)
} catch (exc: DNSSECVerificationException) {
  throw AnotherException("DNSSEC verification failed", exc)
}
```

**Comment by gnarea** [comment]
Hi @ibauersachs 👋🏾 I was wondering if you have any further thoughts on this?

I implemented the API I described above in a prototype. Check out [`DNSSECLookup.kt`](https://github.com/VeraDomains/poc/blob/c92f8c1/vera-lib/src/main/java/tech/relaycorp/vera/core/utils/dnssec/DNSSECLookup.kt) (this is what I originally called `DNSSECVerifier`). [It required minimal changes to dnsjava](https://github.com/dnsjava/dnsjava/compare/master...gnarea:dnsjava:public-dnssec-validation), just to expose a few things as `public`, which wouldn't be necessary if we implement `DNSSECLookup` or something like it.

What do you think about it? I'm happy to implement it in Java and propose a PR.

**Comment by ibauersachs** [comment]
Hey, sorry for the late reply. I thought a bit about your longer message from June, then forgot about it. And unfortunately I wasn't notified about the last comment (or missed it).

I'm still a bit confused about about what you're trying to achieve. The sample and PoC you mention only cover the very happy path: all records exist, the entire chain is signed, a single set of DS/DNSKEY records and signatures, single-label domain names only, no CNAME. What about the non-happy paths? E.g. multi-label domain names or NODATA responses? That stuff isn't handled by `ValUtils`.

I don't quite see why implementing the `Resolver` interface would be too complicated. True, it has a bunch of methods, but most of them can be just left empty for your use case, only `sendAsync` really needs an implementation (see `org.xbill.DNS.SimpleResolver#sendAsync` for how the tests do this).
I'll get back to my question from earlier: did you have a look at the unit tests? I think they do exactly what you're looking for: most of them were built by sending a query using the `ValidatingResolver`, recording all queries and replies into a file, and using that file to run the tests offline in the future. Instead of a file, you could use a database. The test `org.xbill.DNS.dnssec.TestPositive#testValidExising` is probably the easiest example for the happy path of your PoC.

However, if I still misunderstand what you need, I'm open to a simple wrapper API around the existing methods. But it needs to be able to cover all cases, not just happy paths.

@nresare contacted me offline and might have an idea too.

**Comment by nresare** [comment]
My thought was that ValidatingResolver is already backed by the headResolver provided in the constructor. A ValidatingResolver will delegate the lookup of all the records it needs to validate a specific records to this headResolver. 

If you implement a headResolver that returns the relevant entries but also saves them into some persistent storage, this would give you what you are looking for when it comes to creating the needed data to validate a specific record.

It also seems doable to create a headResolver that would respond to queries for those same records by reading the data from say a file, and use the currently exposed validation logic to verify the dnssec signatures offline.

**Comment by gnarea** [comment]
Hi @ibauersachs and @nresare! Thank you so much for taking the time to look into this -- I really appreciate it!

You're right @ibauersachs, the PoC is only dealing with the happy path. That was meant to be an incomplete, throwaway prototype. My thinking was that the final implementation of `DNSSECLookup` would also deal with anything `ValUtils` isn't meant to deal with.

@nresare, I quite like your idea. I think it'd work for me and wouldn't require any change to dnsjava. I'm going to create a PoC and will get back to you.

**Comment by nresare** [comment]
That was pretty much what I had in mind, yes. 

Maybe `CachingResolver` isn't the best name as the prefix caching typically has a meaning that is distinct from this use case. I would go with `OfflineResolver` or something like that, but I digress.

Do you feel like this resolves the issue?

**Comment by gnarea** [comment]
Excellent. Agreed re: naming 👍🏾 

Yeah, this resolves the issue so I'll go ahead and close it. Thank you so much once again!

**Comment by ibauersachs** [comment]
That's pretty much what I meant too, obviously @nresare was better in formulating it. Thanks!

@gnarea Re. the `OfflineResolver` example: make sure to cache the entire `Message` by Name/Type/Class + Time and not individual records or just the answer section. Otherwise you'll mix up responses that don't belong together or have incomplete data for later validation. And as for the binary storage, luckily DNS has a perfect binary serialization - the wire format :-)

Good luck with your project!

**Comment by gnarea** [comment]
Good spot @ibauersachs! 👍🏾 Thank you!
