### ISSUE TITLE
Lookup fails to return SOA records for subdomains

### ISSUE THREAD

**Issue by Spizzinho** [dnsjava/dnsjava#275]
I am having an issue when trying to retrieve the SOA record for a subdomain using the dnsjava library. The lookup is returning null even though the subdomain exists and has a valid SOA record.

Example:
When trying to get the SOA record for the subdomain "sub.example.com" using the following code:

```
var domain = getBaseDomainName("sub.example.com");
var records = new Lookup(domain, Type.SOA).run();
// records array is always null
```

The records variable is returning null, even though the subdomain "sub.example.com" has a valid SOA record.

This issue only occurs when trying to retrieve the SOA record for a subdomain, and not for a top level domain.

I would appreciate if this issue could be looked into.

**Comment by ibauersachs** [comment]
Can you please provide a full example with a public domain? I'm not sure what e.g. `getBaseDomainName` in your example does, but assuming it returns `example.com.`, then I get the expected answer. If the following example doesn't work for you either, please enable trace-level logging for dnsjava and maybe a Wireshark recording.

```java
import java.util.Arrays;
import org.xbill.DNS.Lookup;
import org.xbill.DNS.Record;
import org.xbill.DNS.Resolver;
import org.xbill.DNS.SimpleResolver;
import org.xbill.DNS.Type;

public class Test3 {
  public static void main(String[] args) throws Exception {
    Resolver r = new SimpleResolver("8.8.8.8");
    for (String domain : new String[] {"example.com", "z01.azurefd.net"}) {
      Lookup l = new Lookup(domain, Type.SOA);
      l.setResolver(r);
      l.setCache(null);
      Record[] results = l.run();
      if (results != null) {
        System.out.println(Arrays.asList(results));
      } else {
        System.out.println(l.getErrorString());
      }
    }
  }
}
```

Which results in:
```text
[example.com.		3600	IN	SOA	ns.icann.org. noc.dns.icann.org. 2022091194 7200 3600 1209600 3600]
[z01.azurefd.net.	3384	IN	SOA	ns1-35.azure-dns.com. azuredns-hostmaster.microsoft.com. 1 3600 300 2419200 300]
```

**Comment by ibauersachs** [comment]
`sub.example.com` doesn't exist.
If you mean this as an example, please don't, use an actually existing public domain name that I can verify. I've already said this in my previous reply.

**Comment by Spizzinho** [comment]
ubuntuwebserver.westus.cloudapp.azure.com this can be verified

**Comment by SoylentBob** [comment]
> ubuntuwebserver.westus.cloudapp.azure.com this can be verified

Subdomains usually don't have SOA records, unless they are subdelegated. Therefor it is expected, as the javadoc states:

> Returns: The answers, or null if none are found

**Comment by ibauersachs** [comment]
`westus.cloudapp.azure.com` has a SOA and is properly returned in the example I posted above. `ubuntuwebserver.westus.cloudapp.azure.com` is, as @SoylentBob properly points out, a subdomain, but not delegated and thus doesn't have a SOA. You can verify this also with `dig @8.8.8.8 -t SOA ubuntuwebserver.westus.cloudapp.azure.com`.

**Comment by bitroniq** [comment]
@ibauersachs Do I have to iterate over all subdomains until I get the SOA record?

1. `ubuntuwebserver.westus.cloudapp.azure.com` - null
2. `westus.cloudapp.azure.com` - `westus.cloudapp.azure.com. 60   IN      SOA     ns1-02.azure-dns.com.`

Is this how I should use it?

**Comment by ibauersachs** [comment]
You might want to try using the `Resolver` interface directly instead of going via `Lookup`. This gives you access to the authority section which should contain the next matching SOA record.

**Comment by bitroniq** [comment]
I'll provide my use-case/story to better understand the problem I'm trying to solve with `dnsjava`

* **AS** a QA-Automation Engineer
* **I NEED TO** check `A/AAAA` DNS record for the given **FQDN** by using **SOA** nameserver to avoid TTL and cached values on public DNS resolvers
* SO THAT I can verify if the backend system created or deleted DNS record (A/AAAA) for given FQDN


As plan B we are going to setup on-prem/inhouse Unbound DNS (recursive DNS resolver) and always use it - as it recursively resolves the name starting from root servers.
* https://docs.pi-hole.net/guides/dns/unbound/

But I'd prefer to use pure Java implementation with `dnsjava`. All I need to know is the SOA for a particular FQDN, to get the `A/AAAA` records from SOA namerver 
* this way I have trusted and near real-time results to assert if our backend created/deleted/updated the DNS records.

**Comment by ibauersachs** [comment]
@bitroniq Don't you know the authoritative server(s) in this case anyway?
Otherwise, as mentioned, the `Resolver` interface provides you the complete DNS reply from a recursive resolver and should contain the SOA record in the authority section. You can then use that record to use `Lookup` with the nameserver from the SOA (but beware that `Lookup` also has a cache, you might want to use the `Resolver` interface again directly).

**Comment by Spizzinho** [comment]
I just managed to make it to work with the `Resolver ` as suggested above. 

Thank you!

**Comment by bitroniq** [comment]
@ibauersachs 

> the `Resolver` interface provides you the complete DNS reply from a **recursive resolver**

I think this should do the job.

There is no need for SOA if we can get the recursive reply - same as the DNS unbound (https://docs.pi-hole.net/guides/dns/unbound/) is doing. 

Thanks a lot @ibauersachs
