### ISSUE TITLE
Modern vs Legacy API in light of Virtual Threads

### ISSUE THREAD

**Issue by cowwoc** [dnsjava/dnsjava#312]
Now that virtual threads are a standard part of Java, you might want to revisit the wording of https://github.com/dnsjava/dnsjava/blob/master/EXAMPLES.md#get-the-mx-target-and-preference-of-a-name-modern and ensure that both "modern" and "legacy" APIs have equal functionality. Synchronous APIs are a lot easier to work with and, as a JDK 21, they are the preferred approach for most use-cases.

**Comment by ibauersachs** [comment]
The `Lookup` class is still be considered legacy. Not just because it's synchronous, but mostly because of all the static configuration and non-obvious API. `LookupSession` has the same functionality as of today, and it should be perfectly capable of running in virtual threads by passing an executor (e.g. via `Executors.newVirtualThreadPerTaskExecutor()`). The async result of a lookup can be turned synchronous again by calling `CompletableFuture.get()`.
So at best, I could imagine an additional synchronous `LookupSession.run()` method. However, using it would be bad on Java < 21 (or even in 21+ without explicitly running on virtual threads) and thus I'm most likely not adding that for the foreseeable future.

**Comment by cowwoc** [comment]
Agreed. Thanks for the clarification.
