### ISSUE TITLE
Not behaving great under multi-threading execution.

### ISSUE THREAD

**Issue by jfarjona** [dnsjava/dnsjava#353]
Great library, thanks for doing all this work.

I could not find the root cause, but when executing queries in parallel of any type, the network listener seems to lose packets, and get confused.  Under tcpdump, I could see that the responses were sent to the software, but it seems to miss them.

I put together a test to see if I could find the cause, but I failed to do so.

You can checkout the tiny project at:  https://github.com/jfarjona/dnsjavatest

Run it.  On Win and Linux boxes, same issue:  a query of 92 A records in parallel requires 44 retries (i.e., no parallelism); while in sequential mode I get zero retries.

Used release 3.6.2.

Note: I use different resolvers, because in my use case I need to check different resolvers worldwide to ensure that DNS records are replicated.

Cheers,

Juan

**Comment by ibauersachs** [comment]
I'll have a deeper look, but at first glance some usages in your reproducer don't mix well:
- parallel streams (which use the default thread pool)
- Thread.sleep()
- and Lookup.

The Lookup class uses a blocking wait the resolver's Future (on the default thread pool). Probably the thread pool is simply exhausted and cannot process the answers before running into a timeout.
Try to use the newer LookupSession, which is fully async.

Also, some servers limit the number of requests via the same TCP connection (in violation of RFCs, but since you see the answers in tcpdump this doesn't seem to be the issue here).

**Comment by ibauersachs** [comment]
Did you try using `LookupSession`? What are the results?

**Comment by jfarjona** [comment]
Hi!  Yes, I didn but in my big application code.  I see many packets in wireshark with errors (SYNC errors mainly).  I will update the sample code I published for you, by using LookupSession, and will include the wireshark flow if I see the same problems.  Will do that on the weekend,
