### ISSUE TITLE
Use iphlpapi for Windows resolution

### ISSUE THREAD

**Issue by kingle** [dnsjava/dnsjava#55]
ResolverConfig currently parses ipconfig to grab DNS information as a fallback.  With the sun ResolverConfiguration implementation possibly going away in the future, we should consider additional options.  The most promising one is to use the iphlpapi library if on Windows using the (optional scoped) JNA dependency.  Call `GetNetworkParams`:

C++ example code here:
https://docs.microsoft.com/en-us/windows/desktop/api/iphlpapi/nf-iphlpapi-getnetworkparams

**Comment by kingle** [comment]
Wow.  Looks like JNA basically did this for us: https://github.com/java-native-access/jna/blob/cc1acdac02e4d0dda93ba01bbe3a3435b8933dab/contrib/platform/test/com/sun/jna/platform/win32/IPHlpAPITest.java#L114

**Comment by ibauersachs** [comment]
I was looking at a too old JNA version (some 4.x) yesterday and missed that it's now there. Awesome, something less to worry about.

**Comment by kingle** [comment]
One caveat, when I did the testing, it looks like the `GetNetworkParams` only works with IPv4 addresses and doesn't return the IPv6 address like my ipconfig outputs.  There may still need to be some work to make it a better "try-this-before-ipconfig" option on Windows.  We may want to look at the `GetAdaptersAddresses` https://docs.microsoft.com/en-us/windows/desktop/api/iphlpapi/nf-iphlpapi-getadaptersaddresses

**Comment by ibauersachs** [comment]
Just another example of where Java's built-in mechanism for nameserver lookup fails (via Netty/JNDA):
- At home, connected via WiFi and Ethernet
- Both NICs have the providers nameservers assigned via DHCP
- The nameservers are public IPs, but are only accessible from within my ISPs network
- A VPN connection to my office assigns the companys nameservers
- The VPN is the default gateway (with metric=0), so everything goes via the VPN

Netty tries to query the ISPs nameservers and fails since the query reaches them via the public IP of my company. Yuck. Interestingly though, InetAddress.getByName("...") works - `sun.net.dns.ResolverConfiguration.open().nameservers()` contains seven nameservers, including the ones assigned via VPN (IPv4 only, the VPN is dual-stack and assigns nameservers).

**Comment by ibauersachs** [comment]
See branch `windows-dns-search` for a demo of retrieving all DNS servers (IPv4/IPv6) via JNA. Needs cleanup and ordering of interfaces by metric.
